language: java

jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk7
  - openjdk6

before_install: 
  - git clone git@github.com:huxi/sulky.git ~/builds/sulky 
  - pushd ~/builds/sulky 
  - ./gradlew install 
  - popd 

